Repository form-maker/FFF-FE, pull requests merged in 2023-02, with the labels that each got.

#72 feat : 정보 제공 길어지는 부분 수정
  src/components/createForm/createFormPreview/components/Preview.jsx
Labels: feat

#74 feat : 글씨수 추가
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
Labels: feat

#76 fix: 아이디 중복체크 유효성 검사 수정
  src/components/login/LoginScreen.jsx
  src/components/login/logininput/LoiginInputScreen.jsx
  src/components/signUp/SignUpScreen.jsx
Labels: feat, fix

#78 fix: 회원가입 오류수정
  src/components/signUp/SignUpScreen.jsx
Labels: feat, fix

#79 fix, feat : 필수 선택 기능, 비활성 기능 추가
  package.json
  public/img/checked.svg
  public/img/disablePhoneRightArrow.svg
  public/img/home.svg
  src/components/common/buttons/ToggleButton.jsx
  src/components/common/canNotBeUsedForMobile/CanNotBeUsedForMobile.jsx
  src/components/createForm/createFormContainer/CreateFormContainer.jsx
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/calender/CreateFormCalender.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/SelectGift.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/selectGift/SelectNumber.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/LongAndShortDescriptiveForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/Consent.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/LongDescriptiveAnswer.jsx
  src/components/createForm/createFormSide/components/selectType/SelectTypeList.jsx
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/components/MainSurveySummeryCard.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/screen/MyPageContentScreen.jsx
  src/components/stats/statsMainList/components/DailyUserStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/LongDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/RankStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ScoreStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SingleChoiceStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SlideStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/StarStats.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/Title.jsx
  src/components/survey/components/TurnAPageButtons.jsx
  src/components/survey/components/typeOfSurvey/Consent.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/EndSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/components/survey/components/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/components/typeOfSurvey/ShortDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/SlideSurvey.jsx
  src/components/survey/components/typeOfSurvey/StarSurvey.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/pages/CreateForm.jsx
  src/pages/MyPage.jsx
  src/pages/Stats.jsx
  src/redux/modules/createFormSlice.js
  src/redux/modules/mainCardListSlice.js
  src/redux/modules/surveySlice.js
  src/styles/global.js
  yarn.lock
Labels: feat, fix

#80 feat : alert창 전체 디자인 변경
  package.json
  public/favicon.png
  public/index.html
  src/components/common/popUp/Alert.jsx
  src/components/common/popUp/Confirm.jsx
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/calender/CreateFormCalender.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/GoalNumber.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/login/LoginScreen.jsx
  src/components/login/logininput/LoiginInputScreen.jsx
  src/components/login/outh/KakaoRedirectHandler.jsx
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/components/DeadlineBox.jsx
  src/components/main/mainContent/components/InfiniteScroll.jsx
  src/components/main/mainContent/components/MainSurveySummeryCard.jsx
  src/components/main/mainContent/components/Sort.jsx
  src/components/main/mainTitle/components/PageTitle.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/hooks/useCopyClipBoard.js
  src/components/signUp/SignUpScreen.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/TurnAPageButtons.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/ShortDescriptiveSurvey.jsx
  src/core/Social.js
  src/layout/Header.jsx
  src/redux/modules/createFormSlice.js
  src/redux/modules/myPageListSlice.js
  src/redux/modules/surveySlice.js
  yarn.lock
Labels: feat

#84 feat : 성능 기능 추가, 메타 오지 태그 추가
  public/Ogtag.png
  public/index.html
  src/components/common/Spinner.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/GoalNumber.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/Consent.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/RankAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SlideBarAnswer.jsx
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/components/DeadlineBox.jsx
  src/components/main/mainContent/components/InfiniteScroll.jsx
  src/components/main/mainContent/components/MainSurveySummeryCard.jsx
  src/components/main/mainContent/components/Sort.jsx
  src/components/stats/statsMainList/components/typeOfStats/SlideStats.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/shared/Router.jsx
Labels: feat

#86 feat : sse 추가
  src/components/survey/components/SurveyView.jsx
Labels: feat

#87 refactor : 형태 통일화
  package.json
  public/Ogtag 2.png
  src/components/common/LargeRoundDiv.jsx
  src/components/common/RoundDiv.jsx
  src/components/common/SurveySummeryCard.jsx
  src/components/common/buttons/ToggleButton.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineLarge.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineMedium.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineSmall.jsx
  src/components/common/buttons/roundButtons/RoundButtonLarge.jsx
  src/components/common/buttons/roundButtons/RoundButtonMedium.jsx
  src/components/common/buttons/roundButtons/RoundButtonMediumWide.jsx
  src/components/common/buttons/roundButtons/RoundButtonSmall.jsx
  src/components/createForm/createFormContainer/CreateFormContainer.jsx
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/CreateFormFinalSelect.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/calender/CreateFormCalender.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/GoalNumber.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/SelectDate.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/SelectGift.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/selectGift/SelectEmoji.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/selectGift/SelectNumber.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/LongAndShortDescriptiveForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/NewForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/ScoreAndStarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/StarAnswer.jsx
  src/components/createForm/createFormPreview/screen/CreateFormPreviewScreen.jsx
  src/components/createForm/createFormSide/components/selectType/SelectType.jsx
  src/components/createForm/createFormSide/components/selectType/SelectTypeList.jsx
  src/components/main/mainContent/components/InfiniteScroll.jsx
  src/components/main/mainContent/components/Sort.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/hooks/useCopyClipBoard.js
  src/components/myPage/myPageTitle/components/MyPageTitle.jsx
  src/components/stats/statsMainList/components/Calender.jsx
  src/components/stats/statsMainList/components/DailyUserStats.jsx
  src/components/stats/statsSortToggle/screen/StatsSortToggleScreen.jsx
  src/components/survey/components/SSE.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/Title.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/EndSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/core/api.jsx
  src/hooks/useExample.jsx
  src/layout/Header.jsx
  src/pages/MyPage.jsx
  src/pages/Stats.jsx
  src/redux/modules/mainCardListSlice.js
  src/redux/modules/statsSlice.js
  src/styles/global.js
  yarn.lock
Labels: refactor

#89 chore : 사용하지 않는 라이브러리 제거
  package.json
  yarn.lock
Labels: chore

#90 rename: 오타수정
  src/components/login/logininput/LoiginInputScreen.jsx
  src/components/login/outh/GoogleLogin.jsx
  src/components/login/outh/KakaoLogin.jsx
  src/components/signUp/SignUpScreen.jsx
  src/pages/GooglePage.jsx
  src/pages/KakaoPage.jsx
  src/pages/OathPage.jsx
  src/shared/Router.jsx
Labels: rename
