Repository form-maker/FFF-FE, pull requests merged in 2023-01, with the labels that each got.

#5 design : 메인 페이지 layout 제작
  .eslintrc.json
  package.json
  setupTest.js
  src/components/common/SurveySummery.test.js
  src/components/common/SurveySummeryCard.js
  src/components/common/buttons/NoOutlineButton.js
  src/components/common/buttons/RoundButton.js
  src/components/main/mainContents/components/CardList.js
  src/components/main/mainContents/screen/MainContentsScreen.js
  src/components/main/mainContents/tests/CardList.test.js
  src/components/main/mainSlide/components/Slide.js
  src/components/main/mainSlide/screen/MainSlideScreen.js
  src/components/main/mainSlide/test/Slide.test.js
  src/constants/env.js
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/pages/Main.jsx
  src/redux/modules/mainSlice.js
  src/shared/Router.jsx
  yarn.lock
Labels: design

#6 design: 로그인 페이지 css작업, 회원가입페이지 css작업중
  package.json
  src/components/login/Login.jsx
  src/components/login/LoginScreen.jsx
  src/components/signUp/SignUp.jsx
  src/components/signUp/SignUpScreen.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/redux/modules/signupSlice.js
  src/shared/cookieControler.js
  yarn.lock
Labels: feat

#9 feat : theme provider 적용
  src/App.js
  src/components/common/buttons/RoundButton.js
  src/components/main/Main.jsx
  src/index.js
  src/redux/config/configstore.js
  src/redux/modules/themeSlice.js
  src/shared/Router.jsx
  src/styles/global.js
  src/styles/theme.js
Labels: feat

#10 메인 페이지와 푸터 헤더를 정리하는 작업 진행
  src/components/common/RoundDiv.js
  src/components/common/SurveySummeryCard.js
  src/components/common/buttons/noOutLineButtons/NoOutLineLarge.js
  src/components/common/buttons/noOutLineButtons/NoOutLineMedium.js
  src/components/common/buttons/noOutLineButtons/NoOutLineSmall.js
  src/components/common/buttons/roundButtons/RoundButtonLarge.js
  src/components/common/buttons/roundButtons/RoundButtonMedium.js
  src/components/common/buttons/roundButtons/RoundButtonSmall.js
  src/components/main/mainContents/components/CardList.jsx
  src/components/main/mainContents/screen/MainContentsScreen.js
  src/components/main/mainDescription/components/MainDescription.js
  src/components/main/mainDescription/screen/MainDescriptionScreen.js
  src/components/main/mainSlide/screen/MainSlideScreen.js
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/pages/CreateForm.jsx
  src/pages/Main.jsx
  src/redux/modules/mainCardListSlice.js
  src/shared/Router.jsx
Labels: feat, design, rename

#12 createForm 페이지 기능 및 레이아웃 제작
  package.json
  src/components/common/RoundDiv.jsx
  src/components/common/SurveySummeryCard.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineLarge.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineMedium.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineSmall.jsx
  src/components/common/buttons/roundButtons/RoundButtonLarge.jsx
  src/components/common/buttons/roundButtons/RoundButtonMedium.jsx
  src/components/common/buttons/roundButtons/RoundButtonSmall.jsx
  src/components/common/typeOfAnswer/CoverAnswer.jsx
  src/components/common/typeOfAnswer/GroupAnswer.jsx
  src/components/common/typeOfAnswer/LongDescriptiveAnswer.jsx
  src/components/common/typeOfAnswer/MultipleChoiceAnswer.jsx
  src/components/common/typeOfAnswer/NewAnswer.jsx
  src/components/common/typeOfAnswer/RankAnswer.jsx
  src/components/common/typeOfAnswer/ScoreAnswer.jsx
  src/components/common/typeOfAnswer/ShortDescriptiveAnswer.jsx
  src/components/common/typeOfAnswer/SingleChoiceAnswer.jsx
  src/components/common/typeOfAnswer/SlideBarAnswer.jsx
  src/components/common/typeOfAnswer/StarAnswer.jsx
  src/components/createForm/createFormMain/components/ArrowButton.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/TurnAPageButtons.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/GroupForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/LongAndShortDescriptiveForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/NewForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/ScoreAndStarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
  src/components/createForm/createFormMain/screen/CreateFromMainScreen.jsx
  src/components/createForm/createFormPreview/components/ArrowButton.jsx
  src/components/createForm/createFormPreview/components/CreateFormMobile.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/screen/CreateFormPreviewScreen.jsx
  src/components/createForm/createFormSide/components/CreateFormNavigationIcon.jsx
  src/components/createForm/createFormSide/components/CreateFormQuestionTypeCard.jsx
  src/components/createForm/createFormSide/components/CreateFormSidebar.jsx
  src/components/createForm/createFormSide/screen/CreateFormSideScreen.jsx
  src/components/main/mainContents/screen/MainContentsScreen.jsx
  src/components/main/mainDescription/screen/MainDescriptionScreen.jsx
  src/pages/CreateForm.jsx
  src/redux/config/configstore.js
  src/redux/modules/createFormSlice.js
  src/redux/modules/exampleSlice.js
  src/shared/Router.jsx
  src/styles/global.js
  src/styles/theme.js
Labels: feat, fix, design

#14 design : main 디자인 수정
  src/components/common/SurveySummeryCard.jsx
  src/components/common/buttons/roundButtons/RoundButtonMedium.jsx
  src/components/login/LoginScreen.jsx
  src/components/main/mainContents/screen/MainContentsScreen.jsx
  src/components/main/mainDescription/components/MainDescription.js
  src/components/main/mainDescription/screen/MainDescriptionScreen.jsx
  src/components/main/mainTitle/components/PageTitle.jsx
  src/components/main/mainTitle/components/TitleBackground.jsx
  src/components/main/mainTitle/screen/MainTitleScreen.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/screen/SurveyScreen.jsx
  src/components/survey/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/typeOfSurvey/RankSurvey.jsx
  src/components/survey/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/typeOfSurvey/ShortDesciptiveSurvey.jsx
  src/components/survey/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/typeOfSurvey/SlideSurvey.jsx
  src/components/survey/typeOfSurvey/StarSurvey.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/pages/Main.jsx
  src/pages/Survey.jsx
  src/redux/config/configstore.js
  src/redux/modules/mainCardListSlice.js
  src/redux/modules/surveySlice.js
  src/shared/Router.jsx
  src/styles/theme.js
  yarn.lock
Labels: design

#15 회원가입, 로그인(일반) 기능 구현 완료
  package-lock.json
  package.json
  public/img/btnG_naver.png
  public/img/g-logo.png
  public/img/kakaotalk_sharing_btn_medium.png
  public/img/kakaotalk_sharing_btn_small_ov.png
  src/components/login/Encrypt.js
  src/components/login/LoginScreen.jsx
  src/components/login/outh/Google.jsx
  src/components/login/outh/Oauth2RedirectHandler.jsx
  src/components/signUp/SignUpScreen.jsx
  src/constants/env.js
  src/core/Social.js
  src/core/api.jsx
  src/index.js
  src/pages/GooglePage.jsx
  src/pages/OathPage.jsx
  src/redux/config/configstore.js
  src/redux/modules/signupSlice.js
  src/shared/Router.jsx
  src/shared/cookieControler.js
  yarn.lock
Labels: feat

#19 마이페이지 제작 및 디자인
  src/components/main/mainContent/components/CardList.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/components/MyPageCategory.jsx
  src/components/myPage/myPageContent/screen/MyPageContentScreen.jsx
  src/components/myPage/myPageTitle/components/MyPageTitle.jsx
  src/components/myPage/myPageTitle/screen/MyPageTitleScreen.jsx
  src/layout/Header.jsx
  src/pages/MyPage.jsx
  src/redux/config/configstore.js
  src/redux/modules/myPageListSlice.js
  src/redux/modules/surveySlice.js
  src/shared/Router.jsx
Labels: feat, design

#21 feat : 통계 페이지 1차 구현, 글로벌 디자인, Theme 수정
  package.json
  src/components/common/buttons/noOutLineButtons/NoOutLineMedium.jsx
  src/components/common/buttons/noOutLineButtons/NoOutLineSmall.jsx
  src/components/common/buttons/roundButtons/RoundButtonMedium.jsx
  src/components/main/mainTitle/components/PageTitle.jsx
  src/components/main/mainTitle/components/TitleBackground.jsx
  src/components/stats/statsHeader/components/DailyUserStats.jsx
  src/components/stats/statsHeader/screen/StatsHeaderScreen.jsx
  src/components/stats/statsMainList/components/Stats.jsx
  src/components/stats/statsMainList/components/StatsList.jsx
  src/components/stats/statsMainList/components/typeOfStats/LongDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/MultiChoiceStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/RankStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ScoreStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ShortDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SingleChoiceStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SlideStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/StarStats.jsx
  src/components/stats/statsMainList/screen/StatsMainListScreen.jsx
  src/components/stats/statusSideBar/components/Calender.css
  src/components/stats/statusSideBar/components/Calender.jsx
  src/components/stats/statusSideBar/screen/StatusSideBarScreen.jsx
  src/layout/Header.jsx
  src/pages/Stats.jsx
  src/redux/config/configstore.js
  src/redux/modules/statsSlice.js
  src/shared/Router.jsx
  src/styles/fonts.js
  src/styles/global.js
  src/styles/theme.js
  yarn.lock
Labels: feat, design

#24 feat: 로그인,회원가입 디자인 완료, 소셜로그인 진행중
  package.json
  public/img/closeeye.png
  public/img/logo.js
  public/img/open eye.png
  src/components/login/LoginScreen.jsx
  src/components/login/outh/Google.jsx
  src/components/login/outh/Oauth2RedirectHandler.jsx
  src/components/signUp/SignUpScreen.jsx
  src/core/Social.js
  src/pages/GPage.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: feat, design

#27 fix : 페이지별 수정사항 반영
  public/img/statsToggleClose.svg
  src/components/common/typeOfAnswer/SlideBarAnswer.jsx
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.css
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormSide/components/CreateFormCard.jsx
  src/components/createForm/createFormSide/components/CreateFormList.jsx
  src/components/createForm/createFormSide/components/CreateFormSidebar.jsx
  src/components/createForm/createFormSide/screen/CreateFormSideScreen.jsx
  src/components/main/mainContent/screen/MainContentScreen.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/screen/MyPageContentScreen.jsx
  src/components/stats/statsMainList/components/typeOfStats/LongDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ShortDescriptiveStats.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/components/survey/components/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/components/typeOfSurvey/ShortDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/SlideSurvey.jsx
  src/components/survey/components/typeOfSurvey/StarSurvey.jsx
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/pages/MyPage.jsx
  src/redux/modules/myPageListSlice.js
  src/redux/modules/statsSlice.js
  src/redux/modules/surveySlice.js
Labels: fix

#28 회원가입 기능추가, 디자인 수정
  src/components/login/LoginScreen.jsx
  src/components/login/outh/Google.jsx
  src/components/signUp/SignUpScreen.jsx
  src/shared/Router.jsx
Labels: feat, design

#33 fix : 페이지별 기능 수정
  .babelrc
  package.json
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/calender/CreateFormCalender.jsx
  src/components/stats/statsMainList/components/Calender.jsx
  src/layout/Header.jsx
  src/redux/modules/createFormSlice.js
  src/redux/modules/surveySlice.js
  src/styles/global.js
  yarn.lock
Labels: feat, fix

#34 feat : font 추가
  src/styles/fonts/Pretendard-Black.woff
  src/styles/fonts/Pretendard-Bold.woff
  src/styles/fonts/Pretendard-ExtraBold.woff
  src/styles/fonts/Pretendard-ExtraLight.woff
  src/styles/fonts/Pretendard-Light.woff
  src/styles/fonts/Pretendard-Medium.woff
  src/styles/fonts/Pretendard-Regular.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  src/styles/fonts/Pretendard-Thin.woff
Labels: feat

#35 fix : fonts 적용
  public/index.html
  src/styles/fonts.js
  src/styles/fonts/Pretendard-Black.woff
  src/styles/fonts/Pretendard-Bold.woff
  src/styles/fonts/Pretendard-ExtraBold.woff
  src/styles/fonts/Pretendard-ExtraLight.woff
  src/styles/fonts/Pretendard-Light.woff
  src/styles/fonts/Pretendard-Medium.woff
  src/styles/fonts/Pretendard-Regular.woff
  src/styles/fonts/Pretendard-SemiBold.woff
  src/styles/fonts/Pretendard-Thin.woff
  src/styles/global.js
Labels: fix

#36 refactor : 불필요 파일 삭제 및 위치 변경
  package.json
  src/components/common/typeOfAnswer/RankAnswer.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/GroupAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/LongDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/MultipleChoiceAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/NewAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/RankAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ScoreAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ShortDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SingleChoiceAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SlideBarAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/StarAnswer.jsx
  yarn.lock
Labels: fix, refactor

#38 feat : 페이지별 접근 권한 수정
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/survey/components/SurveyView.jsx
  src/redux/modules/surveySlice.js
Labels: feat, fix

#39 feat : 파일 다운 받는 기능 추가
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/stats/statsHeader/components/StatsSubHeader.jsx
Labels: feat

#37 소셜 로그인 URL수정, 회원가입 버그 수정
  public/index.html
  public/survey.ico
  src/components/login/LoginScreen.jsx
  src/components/signUp/SignUpScreen.jsx
  src/constants/env.js
Labels: fix

#41 feat: 서버요청 변경
  src/core/Social.js
Labels: fix

#44 fix: 로그인 화면 수정, 기타 주석제거
  package.json
  src/components/login/Encrypt.js
  src/components/login/LoginScreen.jsx
  src/components/login/outh/Google.jsx
  src/constants/env.js
  src/core/Social.js
  yarn.lock
Labels: fix

#47 로그인, 회원가입 페이지 수정
  src/components/login/LoginScreen.jsx
  src/components/login/outh/GoogleRedirectHandler.jsx
  src/components/login/outh/KakaoRedirectHandler.jsx
  src/components/signUp/SignUpScreen.jsx
  src/pages/GPage.jsx
  src/pages/GooglePage.jsx
  src/pages/OathPage.jsx
  src/shared/Router.jsx
Labels: feat, fix, design

#49 fix : slide 1차 수정
  src/components/createForm/createFormPreview/components/typeOfAnswer/SlideBarAnswer.jsx
Labels: fix

#50 refactor : 메인 페이지, 마이페이지, 설문 통계 페이지, 설문 응답 페이지 리팩토링
  src/components/common/LargeRoundDiv.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SlideBarAnswer.jsx
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/components/MainSurveySummeryCard.jsx
  src/components/main/mainContent/components/Sort.jsx
  src/components/main/mainContent/screen/MainContentScreen.jsx
  src/components/main/mainTitle/components/PageTitle.jsx
  src/components/main/mainTitle/components/TitleBackground.jsx
  src/components/main/mainTitle/screen/MainTitleScreen.jsx
  src/components/myPage/myPageContent/components/MyPageCardList.jsx
  src/components/myPage/myPageContent/components/MyPageCategory.jsx
  src/components/myPage/myPageContent/components/MySurveySummeryCard.jsx
  src/components/myPage/myPageContent/components/Sort.jsx
  src/components/myPage/myPageContent/components/StatusButton.jsx
  src/components/myPage/myPageContent/screen/MyPageContentScreen.jsx
  src/components/myPage/myPageTitle/components/MyPageTitle.jsx
  src/components/myPage/myPageTitle/screen/MyPageTitleScreen.jsx
  src/components/stats/statsHeader/components/StatsMainHeader.jsx
  src/components/stats/statsHeader/components/StatsSubHeader.jsx
  src/components/stats/statsHeader/screen/StatsHeaderScreen.jsx
  src/components/stats/statsMainList/components/Calender.jsx
  src/components/stats/statsMainList/components/DailyUserStats.jsx
  src/components/stats/statsMainList/components/Stats.jsx
  src/components/stats/statsMainList/components/StatsCategory.jsx
  src/components/stats/statsMainList/components/StatsList.jsx
  src/components/stats/statsMainList/components/Title.jsx
  src/components/stats/statsMainList/components/statsContainer/StatsCommentContainer.jsx
  src/components/stats/statsMainList/components/statsContainer/StatsHeaderContainer.jsx
  src/components/stats/statsMainList/components/typeOfStats/LongDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/MultiChoiceStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/RankStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ScoreStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/ShortDescriptiveStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SingleChoiceStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/SlideStats.jsx
  src/components/stats/statsMainList/components/typeOfStats/StarStats.jsx
  src/components/stats/statsMainList/screen/StatsMainListScreen.jsx
  src/components/stats/statsSortToggle/screen/StatsSortToggleScreen.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/Title.jsx
  src/components/survey/components/TurnAPageButtons.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/components/survey/components/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/components/typeOfSurvey/ShortDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/SlideSurvey.jsx
  src/components/survey/components/typeOfSurvey/StarSurvey.jsx
  src/components/survey/screen/SurveyScreen.jsx
  src/layout/Header.jsx
  src/pages/Main.jsx
  src/pages/MyPage.jsx
  src/pages/Stats.jsx
  src/pages/Survey.jsx
  src/redux/modules/surveySlice.js
Labels: refactor

#51 refactor : 레이아웃, 설문제작 페이지 리팩토링
  src/components/common/hooks/useToggleShow.jsx
  src/components/createForm/createFormHeader/screen/CreateFormHeaderScreen.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/CreateFormPageNumber.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/TurnAPageButtons.jsx
  src/components/createForm/createFormMain/components/calender/CreateFormCalender.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/GroupForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/LongAndShortDescriptiveForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/NewForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/ScoreAndStarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
  src/components/createForm/createFormMain/screen/CreateFormMainScreen.jsx
  src/components/createForm/createFormPreview/components/ArrowButton.jsx
  src/components/createForm/createFormPreview/components/CreateFormMobile.jsx
  src/components/createForm/createFormPreview/components/PhoneTurnAPageButtons.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/GroupAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/LongDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/MultipleChoiceAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/NewAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/RankAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ScoreAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ShortDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SingleChoiceAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SlideBarAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/StarAnswer.jsx
  src/components/createForm/createFormPreview/screen/CreateFormPreviewScreen.jsx
  src/components/createForm/createFormSide/components/CreateFormCard.jsx
  src/components/createForm/createFormSide/components/CreateFormList.jsx
  src/components/createForm/createFormSide/components/CreateFormQuestionTypeCard.jsx
  src/components/stats/statsMainList/components/typeOfStats/ScoreStats.jsx
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/pages/CreateForm.jsx
Labels: refactor

#54 feat, fix, design : 페이지 전반 문제 부분 수정
  public/img/circleClose.svg
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/SelectGift.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
  src/components/createForm/createFormMain/screen/CreateFormMainScreen.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ScoreAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/StarAnswer.jsx
  src/components/createForm/createFormSide/components/CreateFormCard.jsx
  src/components/createForm/createFormSide/components/CreateFormList.jsx
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainTitle/components/PageTitle.jsx
  src/components/myPage/myPageContent/hooks/useCopyClipBoard.js
  src/components/stats/statsMainList/components/StatsCategory.jsx
  src/components/stats/statsSortToggle/screen/StatsSortToggleScreen.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/components/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/StarSurvey.jsx
  src/layout/Footer.jsx
  src/redux/modules/createFormSlice.js
  src/styles/fonts.js
  src/styles/theme.js
Labels: feat, fix, design, remove

#55 feat : 로그 안보이게 처리
  public/index.html
Labels: feat

#56 feat : 선물 관련 내용 메인 및 설문 응답 페이지 기능 구현
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/components/MainSurveySummeryCard.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
Labels: feat

#52 fix: 오타수정 및 버그수정
  public/img/Google.png
  public/img/g-logo.png
  public/img/kakao.png
  public/img/kakaotalk_sharing_btn_medium.png
  public/img/kakaotalk_sharing_btn_small_ov.png
  public/img/naver.png
  src/components/login/LoginScreen.jsx
  src/components/login/outh/KakaoRedirectHandler.jsx
  src/components/signUp/SignUpScreen.jsx
  src/core/Social.js
  src/shared/Router.jsx
Labels: fix, design

#58 feat : 로그인 관련 주석 처리
  src/components/login/LoginScreen.jsx
Labels: feat

#59 fix : 푸터 반응형 수정, build 내용 수정
  package.json
  src/layout/Footer.jsx
Labels: fix

#61 fix: 글씨체, 잘못 들어갔던 정보 오류 수정
  src/components/main/mainContent/components/CardList.jsx
  src/components/main/mainContent/screen/MainContentScreen.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/redux/modules/surveySlice.js
Labels: fix

#62 fix : 설문 응답, 설문 제작 폼 깨지는 부분 수정
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/LongAndShortDescriptiveForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/RankForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/ScoreAndStarForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SingleAndMultiChoiceForm.jsx
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.css
  src/components/createForm/createFormMain/components/questionTypesForm/SlideBarForm.jsx
  src/components/createForm/createFormMain/screen/CreateFormMainScreen.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/CoverAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/LongDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/MultipleChoiceAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/RankAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/ShortDescriptiveAnswer.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/SingleChoiceAnswer.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/Title.jsx
  src/components/survey/components/typeOfSurvey/CoverSurvey.jsx
  src/components/survey/components/typeOfSurvey/EndSurvey.jsx
  src/components/survey/components/typeOfSurvey/LongDescriptiveSurvey.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/RankSurvey.jsx
  src/components/survey/components/typeOfSurvey/ScoreSurvey.jsx
  src/components/survey/components/typeOfSurvey/SingleChoiceSurvey.jsx
  src/components/survey/components/typeOfSurvey/StarSurvey.jsx
Labels: fix

#64 feat: 로그인(소셜 포함), 회원가입 버그 수정
  src/components/login/LoginScreen.jsx
  src/components/login/outh/GoogleRedirectHandler.jsx
  src/components/login/outh/KakaoRedirectHandler.jsx
  src/components/signUp/SignUpScreen.jsx
  src/core/Social.js
  src/shared/Router.jsx
Labels: feat, fix

#65 fix : 오타 수정 및 console log 안보이게 처리
  public/index.html
  src/components/createForm/createFormMain/components/questionTypesForm/SurveyCoverForm.jsx
Labels: fix

#66 fix : 오타 및 x 수정
  src/components/createForm/createFormSide/components/CreateFormCard.jsx
  src/components/survey/components/SurveyView.jsx
Labels: fix

#68 feat,fix : 정보동의 폼 추가, 선물 찌그러지는 부분 수정
  public/img/CONSENT.svg
  public/index.html
  src/components/createForm/createFormMain/components/CreateFormFinalSelect.jsx
  src/components/createForm/createFormMain/components/CreateFormInput.jsx
  src/components/createForm/createFormMain/components/QuestionForm.jsx
  src/components/createForm/createFormMain/components/createFormFinalSelect/selectGift/EmojiPicker.css
  src/components/createForm/createFormMain/components/questionTypesForm/Consent.jsx
  src/components/createForm/createFormPreview/components/Preview.jsx
  src/components/createForm/createFormPreview/components/typeOfAnswer/Consent.jsx
  src/components/createForm/createFormSide/components/selectType/SelectTypeList.jsx
  src/components/survey/components/SurveyView.jsx
  src/components/survey/components/typeOfSurvey/Consent.jsx
  src/components/survey/components/typeOfSurvey/MultipleChoiceSurvey.jsx
Labels: feat, fix
